-- Write a SQL query to retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue.

SELCET c.name AS category_name,
SUM(oi.unit_price * oi_quantity) As total_revenue
FROM categories c 
INNER JOIN product p ON c.category_id = p.category_id
INNER JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY c.categrory_name
ORDER BY total_revenue DESC;
